version: '3.8'

services:
  frontend:
    image: node:20-alpine
    ports:
      - '80:5173' # Vite dev server
    volumes:
      - .:/app # Bind mount your code
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: yarn dev --host
