version: '3.8'

services:
  vue-dev:
    build: .
    ports:
      - '5173:5173' # Vite dev server
    volumes:
      - .:/app # Bind mount your code
      - /app/node_modules # Avoid host <-> container node_modules conflict
    environment:
      - NODE_ENV=development
    command: yarn dev --host
